"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class body_record_lcmt(object):

    __slots__ = ["q"]

    __typenames__ = ["float"]

    __dimensions__ = [[27]]

    def __init__(self):
        self.q = [ 0.0 for dim0 in range(27) ]
        """ LCM Type: float[27] """

    def encode(self):
        buf = BytesIO()
        buf.write(body_record_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>27f', *self.q[:27]))

    @staticmethod
    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != body_record_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return body_record_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = body_record_lcmt()
        self.q = struct.unpack('>27f', buf.read(108))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if body_record_lcmt in parents: return 0
        tmphash = (0x27f19bfc1df30058) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if body_record_lcmt._packed_fingerprint is None:
            body_record_lcmt._packed_fingerprint = struct.pack(">Q", body_record_lcmt._get_hash_recursive([]))
        return body_record_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", body_record_lcmt._get_packed_fingerprint())[0]

